---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app2
  namespace: gitops-app2
  labels:
    chart: quickstart-application
spec:
  chart:
    spec:
      chart: .helm
      sourceRef:
        kind: GitRepository
        name: gitops-app2
        namespace: wego-system
  interval: 5m0s

