---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-app2
  namespace: wego-system
spec:
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: gitops-app2
  interval: 30s
  targetNamespace: gitops-app2

